### ISSUE TITLE
revise and extend SysML specification

### ISSUE THREAD

**Issue by kiniry** [GaloisInc/HARDENS#30]
- [x] bump our SysML v2 Pilot Implementation version to the January 2022 release
- [ ] revise scenarios to reflect final design and V&V (see #45)
- [ ] revise events to reflect final design and V&V (see #44)
- [ ] write definitions for all `Project Glossary` concepts that are incomplete
- [x] further refactor and collect `Project Glossary` terms into sub-packages
- [ ] alphabetize `Project Glossary`, per-sub-package, per-package
- [ ] complete `Physical Architecture` by wiring up _parts_ using _cables_ and _channels_
- [ ] complete `RTS Implementation Artifacts` specification by defining dataflow on provided items
- [ ] encode Cryptol state machine into SysML state machine
- [ ] core ASM specification in SysML (depends on #44 for event specs)
- [ ] specify model normal behavior and exceptional behaviors, lifted from the Cryptol model, using Occurences, Time Slices, and Snapshots, mapping Occurences to Messages on device driver actions
- [ ] ensure that the appropriate invariants of the ACSL model are lifted to SysML Constraint
- [ ] figure out the appropriate means by which to lift and express ACSL models and contracts into the SysML model
- [ ] transliterate FRET requirements into SysML requirements
- [x] transliterate NRC characteristics into SysML requirements
- [ ] add any necessary traceability properties and annotations that are not implicitly covered by our methodology
- [ ] after Lando/Lobot feature model is complete, lift that model into SysML as a variability model
- [ ] itemize necessary architecture view and generate beautiful renderings of every view for presentations and report
