### ISSUE TITLE
handle all outstanding `@todo` annotations in Lando model

### ISSUE THREAD

**Issue by kiniry** [GaloisInc/HARDENS#40]
Our Lando model has over 200 outstanding `@todo` annotations in places where we have to drop in definitions/explanations for domain engineering model elements.  

These explanations are not strictly necessary for the first implementation of the model, but need to be complete for final delivery of the system.  We use them, in part, to check the completeness of the domain model and to generate the final glossary for the system.

This issue will track our progress on updating these explanations.

 - [x] `acronyms.lando` 78 remaining
 - [x] `architecture.lando` 31 remaining
 - [x] `dataflow.lando` 13 remaining
 - [x] `glossary.lando` 86 remaining
 - [x] `hardware.lando` 19 remaining
 - [x] `requirements.lando` needs to be filled in

**Comment by kiniry** [comment]
I'm using GPT-4 to revise these specifications now.  I provided a prelude to explain HARDENS and RDE, then bootstrapped its understanding with an EBNF grammar of Lando and an explanation of our approach to domain engineering, then provided each partial specification in turn, reviewing the output for inclusion here.  [Here is the resulting transcript](https://chat.openai.com/share/d4366c58-9f4e-43d6-a59d-6f29d3f6a992) of my co-design with GPT-4.
